# Generated by Django 4.0.1 on 2022-01-28 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 17, 31, 9, 276861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 17, 31, 9, 275861, tzinfo=utc)),
        ),
    ]
