# Generated by Django 4.0.1 on 2022-01-28 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_post_creation_date_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 17, 33, 0, 283388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 17, 33, 0, 282388, tzinfo=utc)),
        ),
    ]
