# Generated by Django 4.0.1 on 2022-01-28 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_rename_is_stuff_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 18, 24, 3, 694463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 18, 24, 3, 693463, tzinfo=utc)),
        ),
    ]
