# Generated by Django 4.0.1 on 2022-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0009_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
